### ISSUE TITLE
Refactoring code src/upgrades/1.0.0/chat_upgrade.js

### ISSUE THREAD

**Issue by aattiyah** [CMU-17313Q/NodeBB-F24#32]
Refactor this code to not nest functions more than 4 levels deep.

src/upgrades/1.0.0/chat_upgrade.js

**Comment by aattiyah** [comment]
I would like to work on this please!

**Comment by EduardoFF** [comment]
The current tests do not cover this file. Therefore, you have two options to complete the last part of P1B:

(a) Write tests from scratch to cover that file OR
(b) Select another file currently covered by tests (under src/) that is NOT fully covered and do the following:
- Increase the coverage of the file by at least one line.
- Commit your changes to the same branch referenced in the PR.
- For the final part of the task (manual testing), activate at least one function of the file you selected from the user interface (UI).
